### ISSUE TITLE
varan is quitting upon launch

### ISSUE THREAD

**Issue by wgharib** [popitsch/varan-gie#1]
INFO [2020-11-23 15:51:52,601]  [Main.java:145] [AWT-EventQueue-0]  Startup  IGV Version user (0)03/06/2019 11:35 AM
INFO [2020-11-23 15:51:52,602]  [Main.java:146] [AWT-EventQueue-0]  Java 13.0.1
INFO [2020-11-23 15:51:52,602]  [DirectoryManager.java:73] [AWT-EventQueue-0]  Fetching user directory...
INFO [2020-11-23 15:51:52,708]  [Main.java:147] [AWT-EventQueue-0]  Default User Directory: $HOME
INFO [2020-11-23 15:51:52,708]  [Main.java:148] [AWT-EventQueue-0]  OS: Mac OS X

ERROR [2020-11-23 15:51:52,765]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NoClassDefFoundError: com/sun/java/swing/plaf/windows/WindowsLookAndFeel
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:848)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:633)
	at com.jidesoft.plaf.LookAndFeelFactory.installJideExtension(LookAndFeelFactory.java:598)
	at org.broad.igv.ui.Main.initializeLookAndFeel(Main.java:320)
	at org.broad.igv.ui.Main.open(Main.java:261)
	at org.broad.igv.ui.Main$1.run(Main.java:99)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 19 more
INFO [2020-11-23 15:51:56,702]  [ShutdownThread.java:49] [Thread-1]  Shutting down
INFO [2020-11-23 15:51:56,709]  [GIE.java:264] [Thread-1]  GIE Directory: /Users/wgharib/igv/gie
INFO [2020-11-23 15:51:56,772]  [GIE.java:310] [Thread-1]  Hours since last autobackup: 0

**Comment by wgharib** [comment]
resolved had to install java 8.

**Comment by popitsch** [comment]
Thanks wgharib, yes varan-gie currently works only with java8 on MacOS. I will update the README accordingly.
